/**
 * Shipment status enum - mirrors backend exactly
 */
export enum ShipmentStatus {
  PENDING = 'PENDING',
  PICKED_UP = 'PICKED_UP',
  IN_WAREHOUSE = 'IN_WAREHOUSE',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  POSTPONED = 'POSTPONED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}

/**
 * Shipment type enum
 */
export enum ShipmentType {
  COD = 'COD',
  PREPAID = 'PREPAID',
  RETURN = 'RETURN',
}

/**
 * Return reason enum
 */
export enum ReturnReason {
  CUSTOMER_NOT_AVAILABLE = 'CUSTOMER_NOT_AVAILABLE',
  CUSTOMER_REFUSED = 'CUSTOMER_REFUSED',
  WRONG_ADDRESS = 'WRONG_ADDRESS',
  PHONE_UNREACHABLE = 'PHONE_UNREACHABLE',
  PRODUCT_DAMAGED = 'PRODUCT_DAMAGED',
  PRODUCT_MISMATCH = 'PRODUCT_MISMATCH',
  COURIER_ACCESS_ISSUE = 'COURIER_ACCESS_ISSUE',
  CUSTOMER_CANCELLED = 'CUSTOMER_CANCELLED',
}
